CREATE DATABASE QuanLyBanQuanAo
USE QuanLyBanQuanAo
GO

CREATE TABLE TaiKhoan(
MaTK VARCHAR(30) PRIMARY KEY ,
TenTK NVARCHAR(30) UNIQUE,
Matkhau NVARCHAR(30),
Chucvu NVARCHAR(30)
)

CREATE TABLE LoaiSP(
MaLoaiSP VARCHAR(20) PRIMARY KEY,
TenLoaiSP NVARCHAR(30),
)

CREATE TABLE ChatLieu(
MaChatLieu VARCHAR(20) PRIMARY KEY,
TenChatLieu NVARCHAR(20)
)

CREATE TABLE MauSac(
MaMauSac VARCHAR(20) PRIMARY KEY,
TenMauSac NVARCHAR(20)
)


CREATE TABLE Size(
MaSize VARCHAR(20) PRIMARY KEY,
TenSize VARCHAR(10)
)

CREATE TABLE SanPham(
MaSanPham VARCHAR(20) PRIMARY KEY,
TenSanPham NVARCHAR(20)
)

CREATE TABLE NhanVien(
MaNhanVien VARCHAR(20) PRIMARY KEY,
Ho NVARCHAR(20),
TenDem NVARCHAR(20),
Ten NVARCHAR(20),
SDT INT,
ChucVu NVARCHAR(20),
DiaChi NVARCHAR(50),
TrangThai INT
)

CREATE TABLE ChiTietSanPham(
MaCTSP VARCHAR(20) PRIMARY KEY,
MaLoaiSP VARCHAR(20) FOREIGN KEY REFERENCES LoaiSP(MaLoaiSP),
MaChatLieu VARCHAR(20) FOREIGN KEY REFERENCES ChatLieu(MaChatLieu),
MaMauSac VARCHAR(20) FOREIGN KEY REFERENCES MauSac(MaMauSac),
MaSize VARCHAR(20) FOREIGN KEY REFERENCES Size(MaSize),
MaSanPham VARCHAR(20)FOREIGN KEY REFERENCES SanPham(MaSanPham),
Mota INT,
GiaBan DECIMAL(10, 2),
TrangThai INT
)


CREATE TABLE HoaDon(
MaHoaDon VARCHAR(20) PRIMARY KEY,
MaNhanVien VARCHAR(20) FOREIGN KEY REFERENCES NhanVien(MaNhanVien),
NgayTao DATE,
NgayThanhToan DATE,
ThanhTien DECIMAL(10, 2),
SDTKH INT,
DiaChi NVARCHAR(50),
TrangThai INT
)

CREATE TABLE HoaDonChiTiet(
MaHoaDon VARCHAR(20) FOREIGN KEY REFERENCES HoaDon(MaHoaDon),
MaCTSP VARCHAR(20) FOREIGN KEY REFERENCES ChiTietSanPham(MaCTSP), 
SoLuong INT,
TenSize VARCHAR(10), 
Kieu NVARCHAR(20),
DonGia DECIMAL,
TrangThai INT
)

CREATE TABLE DoiTra(
MaDoiTra VARCHAR(20) PRIMARY KEY,
MaSanPham VARCHAR(20) FOREIGN KEY REFERENCES SanPham(MaSanPham),
TenSP NVARCHAR(30), 
SoLuong INT,
LyDoDoiTra NVARCHAR(50)
)
